Fixes issue #10 where empty N and FN fields would throw an error
DamienCassou/vdirel pull request #15
Opened 2019-11-04 10:47 UTC by dbankmann

Now just returns an empty string

2019-11-05 08:58 UTC, DamienCassou requested changes
Thank you for your work. Can you please take care of my comments? I will try to fix the build so travis is happy with your PR.

2019-11-05 08:58 UTC, DamienCassou commented on test/vdirel-test.el
> +          (it "contacts without FN or F should return empty string"
can you please move this `it` to the `describe` called "knows how to extract a contact's fullname" and rename it to "when there is neither FN nor F"?

2019-11-05 08:58 UTC, DamienCassou commented on vdirel.el
> +   (if (equal (vdirel--contact-property "N" contact) nil)
I would prefer a different code structure (untested):

```emacs
(or
  (vdirel--contact-property "FN" contact)
  (let ((name (vdirel--contact-property "N" contact)))
    (when name
      (replace-regexp-in-string ";" " " name)))
  "")
```

2019-11-05 09:19 UTC, DamienCassou commented
Can you please also rebase your branch on top of latest `master`? It will hopefully make the travis build pass.

2019-11-05 09:21 UTC, DamienCassou commented
Next time, I suggest you follow the [best practices](https://github.com/magit/magit/wiki/Dedicated-pull-request-branches) to open a PR, it will make both our lifes easier :-). No need to change this PR though, it's ok.

2023-05-16 06:23 UTC, peterhoeg commented
I have addressed this differently in #18 (I wasn't aware of this PR), where we just return the email address for the name to at least give us *something* in case `N` or `FN` are both missing. If the approach in this PR is preferred, I'll change accordingly of course.

2023-05-16 19:40 UTC, DamienCassou commented
I'm closing this PR as the author isn't responding.

2023-05-16 19:40 UTC, closed without merging