Helm action to open file
DamienCassou/vdirel pull request #20
Opened 2021-08-08 07:49 UTC by Titan-C

I wanted to find and edit the files of some of my contacts. I added a new Helm action that lets me jump to the  vcf file and edit it manually.

2021-08-11 18:47 UTC, DamienCassou requested changes
Excellent job, thank you. Can you please just take care of my comment on the docstring?

2021-08-11 18:47 UTC, DamienCassou commented on vdirel.el
> +  "Open file assosiated to CANDIDATE."
can you please rephrase this docstring so it clearly says that `CANDIDATE` is ignored? You can copy/paste from `vdirel--helm-insert-contact-email`.

2021-08-11 18:47 UTC, DamienCassou commented
Did you know about [khardel](https://github.com/DamienCassou/khardel)? I use it instead of vdirel.

2021-08-11 18:47 UTC, DamienCassou commented
khardel has builtin support for contact edition.

2021-08-13 06:08 UTC, Titan-C commented
I had no idea of khardel. It never showed up in any of my searches. It
does seem a lot more practical, only with the extra inconvenience of
installing an extra dependency.

2021-08-13 07:54 UTC, DamienCassou approved these changes
Excellent job! Thank you!

2021-08-13 07:54 UTC, merged

2021-08-13 07:54 UTC, DamienCassou commented
You won't regret installing `khard`, it's a great tool.